### ISSUE TITLE
Rewrite the Readme of Playground

### ISSUE THREAD

**Issue by sadiqevani** [aeternity/aepp-playground#126] opened 2019-05-21 17:03 UTC
- Brief description of the project  (what is the playground, what is used for etc.)
- If there are any requirements for the project
- Description of the current functionalities (editor, configs)
- Some examples and how to use the application

**Comment by maptuhec** [comment] 2019-05-28 14:50
This issue is duplicate of #108

**Closed by maptuhec** 2019-05-28 14:50 UTC
Labels: backlog, enhancement
