### ISSUE TITLE
Unsupported node version 4.2.0. Supported: >= 2.3.0 < 4.0.0 

### ISSUE THREAD

**Issue by eminogrande** [aeternity/aepp-playground#144] opened 2019-08-16 12:40 UTC
When i try to compile a contract with the IDE this error is shown in the console:

![image](https://user-images.githubusercontent.com/3612477/63168210-d7544500-c033-11e9-8b88-e04cf7abba26.png)

**Comment by maptuhec** [comment] 2019-08-27 10:56
@emin Should be fixed now. Can you try and close the issue if you can't reproduce.

Thanks,
Martin

**Closed** 2019-10-16 08:27 UTC
Labels: bug
