### ISSUE TITLE
Transaction build error. {"ownerId":"Field is required"}

### ISSUE THREAD

**Issue by eminogrande** [aeternity/aepp-playground#136] opened 2019-06-26 16:31 UTC
When i try to deploy a contract via https://testing.playground.aepps.com i receive following error:

~ Transaction build error. {"ownerId":"Field is required"} 

![image](https://user-images.githubusercontent.com/3612477/60197833-8e0c2400-9840-11e9-82dc-f593566aedcd.png)

**Comment by maptuhec** [comment] 2019-08-27 10:56
@emin Should be fixed now. Can you try and close the issue if you can't reproduce.

Thanks,
Martin

**Closed** 2019-10-16 08:28 UTC
Labels: bug
